name: First-Workflow

on:
  push:
    branches: [ master ]
    
jobs:
  First-Job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Running Tests
        run: mvn test
